### ISSUE TITLE
First Release Checklist

### ISSUE THREAD

**Issue by li-boxuan** [li-boxuan/Regex-Checker#1]
- [x] Support WIP/DNM check, etc. by default
- [x] Support regex must NOT match (defined by a yaml file)
- [x] Support regex must match
- [x] Support status setting (use in-progress or failure)
- [x] Record demo (gif)
- [x] Write doc (README)
- [x] Add logo
- [x] Case sensitivity support
- [x] Add ESLint check
- [x] Add tests
- [x] Add codecov report
- [x] Add CI

Post-release:
- [ ] Add to probot apps list
- [ ] Promote the app

Not included in this release:
- [ ] Add logs on server side
- [ ] Do not run check if state has not changed
- [ ] Add support for private repositories

**Comment by li-boxuan** [comment]
Closed by https://github.com/li-boxuan/Regex-Checker/releases/tag/v1.0
